### ISSUE TITLE
Error on booting up

### ISSUE THREAD

**Issue by FeelsBadMan1** [Dany-LF/Xyliase#4]
Hello, i downloaded the zipfile then extracted it and run the app.js file and it not worked so i went 1 folder back and typed the node foldername but it output the same issure hopefully someone is able to help me. the issure:
![image](https://user-images.githubusercontent.com/40109798/99887436-bc17b280-2c44-11eb-8c82-cf8152fe8205.png)

**Comment by HideakiAtsuyo** [comment]
Lol... Funny...
